### Accessing, Deleting, and Inserting Elements Into ndarrays

In [1]:
import numpy as np

X = np.array((1, 2, 3, 4, 5))
print(X)

print('1st element:', X[0]) # to access first element 
print('2nd element:', X[1])
print('5th element:', X[4])
# Using negative indices to specify positions from the end of the array
print('1st element:', X[-5])
print('2nd element:', X[-4])
print('5th element:', X[-1])


# modify elements in the array
# access the element and reassign it 
X[3] = 20
print(X)

[1 2 3 4 5]
1st element: 1
2nd element: 2
5th element: 5
1st element: 1
2nd element: 2
5th element: 5
[ 1  2  3 20  5]


In [2]:
#3 by 3 array containing integers 1-9
X = np.arange(1, 10).reshape(3, 3)
print(X)

# Access some elements in that array
print('Element at (0, 0):', X[0, 0])
print('Element at (0, 1):', X[0, 1])
print('Element at (2, 2):', X[2, 2])

X[0, 0] = 20
print(X)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Element at (0, 0): 1
Element at (0, 1): 2
Element at (2, 2): 9
[[20  2  3]
 [ 4  5  6]
 [ 7  8  9]]


In [3]:
# How to add and delete elements
# We delete the first and 5th element like above
X = np.array([1,2,3,4,5,6])
print(X)

X = np.delete(X, [0, 4])
print(X)

[1 2 3 4 5 6]
[2 3 4 6]


In [4]:
Y = np.arange(1, 10).reshape(3, 3)
print(Y)

# delete the first row
W = np.delete(Y, 0, axis=0)
print('\n', W)

# delete first column and last column
V = np.delete(Y, [0, 2], axis=1)
print('\n', V)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

 [[4 5 6]
 [7 8 9]]

 [[2]
 [5]
 [8]]


### numpy.append
#### Syntax:

#### numpy.append(array, values, axis=None)
https://numpy.org/doc/stable/reference/generated/numpy.append.html

We can append values to ndarrays using the np.append(ndarray, elements, axis) function. This function appends the given list of elements to ndarray along the specified axis

In [5]:
# add values to numpy arrays using append function
# takes in an array, a list of elements to append,
# & axis to append it on.
X = np.array([1,2,3,4,5])
print(X)

# append 6 to this 1 rank array
X = np.append(X, 6)
print(X)

# we can append multiple elements say 7, 8 & 10
X = np.append(X, [7, 8, 10])
print(X)

[1 2 3 4 5]
[1 2 3 4 5 6]
[ 1  2  3  4  5  6  7  8 10]


In [6]:
# in a rank 2 array, we can append in a row
Y = np.arange(1, 10).reshape(3, 3)
print(Y)

W = np.append(Y, [[10, 11, 12]], axis=0)
print(W)

# apppend a new column
V = np.append(Y, [[10],[11], [12]], axis=1)
print(V)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3 10]
 [ 4  5  6 11]
 [ 7  8  9 12]]


##### We can insert values to ndarrays using the np.insert(ndarray, index, elements, axis) function. This function inserts the given list of elements to ndarray right before the given index along the specified axis

In [7]:
# inserting values into numpy arrays
# takes in index, elements & axis
x = np.array([1,21,15,60,7])
print(x)
# insert integer between elements 2 and 5
x =np.insert(x, 2, [3, 4])
print(x)

y = np.array([[1, 2, 3], [7, 8, 9]])
print(y)


[ 1 21 15 60  7]
[ 1 21  3  4 15 60  7]
[[1 2 3]
 [7 8 9]]


## numpy.hstack and numpy.vstack
Syntax:

#### numpy.hstack(sequence_of_ndarray)

It returns a stacked array formed by stacking the given arrays in sequence horizontally (column-wise).
[numpy.hstack](https://numpy.org/doc/stable/reference/generated/numpy.vstack.html)

#### numpy.vstack(sequence_of_ndarray)
It returns a stacked array formed by stacking the given arrays, will be at least 2-D, in sequence vertically (row-wise).
[numpy.vstack](https://numpy.org/doc/stable/reference/generated/numpy.vstack.html)
NumPy also allows us to stack ndarrays on top of each other, or to stack them side by side. The stacking is done using either the np.vstack() function for vertical stacking, or the np.hstack() function for horizontal stacking. It is important to note that in order to stack ndarrays, the shape of the ndarrays must match.


In [8]:
# Stack arrays
# We create a rank 1 ndarray 
x = np.array([1,2])

# We create a rank 2 ndarray 
Y = np.array([[3,4],[5,6]])

# We print x
print()
print('x = ', x)

# We print Y
print()
print('Y = \n', Y)

# We stack x on top of Y
z = np.vstack((x,Y))

# We stack x on the right of Y. We need to reshape x in order to stack it on the right of Y. 
w = np.hstack((Y,x.reshape(2,1)))

# We print z
print()
print('z = \n', z)

# We print w
print()
print('w = \n', w)


x =  [1 2]

Y = 
 [[3 4]
 [5 6]]

z = 
 [[1 2]
 [3 4]
 [5 6]]

w = 
 [[3 4 1]
 [5 6 2]]
