In [1]:
## We import NumPy into python
import numpy as np

## We create a 1D ndarray that contains only integers
x = np.array([1, 2, 3, 4, 5])

## Let's print the ndarray we just created using the print () command
print('x = ', x)

x =  [1 2 3 4 5]


In [2]:
## Rank of Array (numpy.ndarray.ndim)
# ndarray.ndim
"""
Returns nunber of array dimensions.
 We refer to 1D as rank 1 array i.e in general N-Dimensional arrays have rank N
"""

'\nReturns nunber of array dimensions.\n We refer to 1D as rank 1 array i.e in general N-Dimensional arrays have rank N\n'

In [3]:
## 1-D array
x = np.array([1, 2, 3])
x.ndim

## 2-D array
Y = np.array([[1,2,3], [4,5,6], [10,11,12]])
Y.ndim

## Here the `zeros()` is an inbuilt function to be studied.
## The tuple (2, 3, 4) passed as an argument represents the shape of the ndarray
y = np.zeros((2, 3, 4))
y.ndim


## numpy.ndarray.shape
#ndarray.shape
# returns a tuple representing the array dimensions

## numpy.dtype - tells us the data-type of the elements.

3

In [4]:
# Using a 1D Array of integers
## we create a 1D ndarray that contains only integers
x = np.array([1, 2, 3, 4, 5])

# print information about x
print('x = ', x)
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype)

x =  [1 2 3 4 5]
x has dimensions: (5,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: int64


In [5]:
## NumPy Data Types
# ndarrays can also hold strings, by providing the np.array() function a python list of strings

# Create a rank 1 ndarray that only contains strings
x = np.array(['Hello', 'Scientist'])

# Print information of x
print('x = ', x)
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype)

# shape attribute tells us that x now has only 2 elements, eventhough it holds a string
# the type() function tells it is an ndarray
# the .dtype attribute tells us that the elements stored in meme=ory as Unicode string of 9 characters

# Numpy requires all elements be stored as the same type & size for computational effeciency, 
# thus is why it determines the maximum string length and assigns a fixed-length string dtype of all element.

x =  ['Hello' 'Scientist']
x has dimensions: (2,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: <U9


In [6]:
# Using a 1-D Array of mixed datatype
# Create a rank 1 ndarray from python lists that conains integers and strings
x = np.array([1, 2, 'World guru'])

# print information of x
print('x = ', x)
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in X are of type:', x.dtype)

# Though python list had mixed data types, elements in x are all same type, namely Unicode strings of 21 characters.
# Unicode string of 21 characters, indicates a fixed-length of string of 21 characters as NumPy upcasts toa ccomodate the longest string in array.

x =  ['1' '2' 'World guru']
x has dimensions: (3,)
x is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: <U21


In [7]:
# Using a 1D Array to demonstrate upcasting in numeric datatype
import numpy as np
# Create a rank 1 ndarray that contains integers
x = np.array([1,2,3])

# create a rank 1 ndarray containing floats
y = np.array([1.0,2.0,3.0])

# Create a rank 1 ndarray that contains int and floats
z = np.array([1, 2.5, 4])

# print dtype of each ndarray
print('The elements in x are of type:', x.dtype)
print('The elements in y are of type:', y.dtype)
print('The elements in z are of type:', z.dtype)

The elements in x are of type: int64
The elements in y are of type: float64
The elements in z are of type: float64


In [8]:
# Using a 2D Array
import numpy as np
Y = np.array([[1,2,3],[4,5,6],[7,8,9], [10,11,12]])

print('Y = \n', Y)

## We print information about Y
print('Y has dimensions:', Y.shape)
print('Y has a total of', Y.size, 'elements')
print('Y is an object of type:', type(Y))
print('The elements in Y are of type:', Y.dtype)

Y = 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Y has dimensions: (4, 3)
Y has a total of 12 elements
Y is an object of type: <class 'numpy.ndarray'>
The elements in Y are of type: int64


In [9]:
# Save the NumPy array to a File
"""Once you create an ndarray, you may want to save it to a file to be read later or to be used by another program.
"""
import numpy as np
## We create a rank 1 ndarray
x = np.array([1, 2, 3, 4, 5])

## We save x into the current directory as 
np.save('my_array', x)


# We load the saved array from our current directory into variable y
y = np.load('my_array.npy')

## We print y
print()
print('y = ', y)
print()

## We print information about the ndarray we loaded
print('y is an object of type:', type(y))
print('The elements in y are of type:', y.dtype)


y =  [1 2 3 4 5]

y is an object of type: <class 'numpy.ndarray'>
The elements in y are of type: int64


In [10]:
import numpy as np

my_list = [1, 2, 3, 4, 5]
np.array(my_list)

array([1, 2, 3, 4, 5])

In [11]:
x = np.zeros((3, 4), dtype=int)
print(x)
print('dtype: ', x.dtype)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
dtype:  int64


In [12]:
a = np.ones((4,6))
print(a)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [13]:
# Creating an array filled with any constant values using the full function
b = np.full((4, 3), 5)
print(b)
print(b.dtype)

[[5 5 5]
 [5 5 5]
 [5 5 5]
 [5 5 5]]
int64


In [14]:
# a fundamental array in linear Algebra is the identity matrix
# A matrix is a two dimensional array with rows and columns.
# an identity matrix is a square shaped matrix that has ones along its main diagonal and zeros everywhere else

# NumPy's eye fucntion can be used to create identity matrices
y = np.eye(5)
print(y)
print('Alternative_2')
"""
Using numPy;s diag function to create a diagonal matrix
"""
y = np.diag([20, 30, 10, 40, 50])
print(y)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Alternative_2
[[20  0  0  0  0]
 [ 0 30  0  0  0]
 [ 0  0 10  0  0]
 [ 0  0  0 40  0]
 [ 0  0  0  0 50]]


In [15]:
# numpy has useful fucntions to generate arrays with specific numerical ranges.

z = np.arange(20)
print(z)

# Reshape converts numpy arrays into any shape
z = np.reshape(z, (4, 5))
print (z)

z = np.reshape(z,(10, 2))
print(z)

# x= np.reshape(z, (5, 5))
# print(z)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]


In [16]:
z = np.arange(4, 10)
print(z)

[4 5 6 7 8 9]


In [17]:
# Create a Numpy array using arange(start_val, stop_val, step_size)
z = np.arange(1, 14, 3)
print(z)

[ 1  4  7 10 13]


In [18]:
# Using numpy linspace function, takes three arguments, start, stop and N
# This returns n evenly spaced numbers from start to stop; both start and stop being inclusive.
z = np.linspace(0, 25, 10)
print(z)

[ 0.          2.77777778  5.55555556  8.33333333 11.11111111 13.88888889
 16.66666667 19.44444444 22.22222222 25.        ]


In [19]:
z = np.linspace(0, 25, 10, endpoint = False)
print(z)

[ 0.   2.5  5.   7.5 10.  12.5 15.  17.5 20.  22.5]


In [20]:
# applying functions as methods, applying different functions in sequence in just one line of code
c = np.linspace(0, 50, 10, endpoint=False).reshape(5, 2)
print(c)
# No need to pass in an array as an argument

[[ 0.  5.]
 [10. 15.]
 [20. 25.]
 [30. 35.]
 [40. 45.]]


In [21]:
# Creating numpy arrays that contain randomn numbers
# i.e when initializing the weights of a neural network
d = np.random.random((3, 3)) # to access the module, then the function in the module
print(d)

# Takes 3 arguments, the lower bound inclusive, the upper bound exclusive, then the shape
rand_int = np.random.randint(4, 15, (3, 2)) # creating random integer arrays in interval
print(rand_int)

[[0.63240551 0.41531777 0.54209247]
 [0.02641777 0.0124372  0.23334962]
 [0.00821559 0.33718106 0.22490419]]
[[ 6  8]
 [ 6  7]
 [ 6 14]]


In [22]:
#  To create numpy arrays with random numbers that satisfy certain stat properties.
 # i.e Random numbers in the array to have an average of zero
# Numpy used to create random arrays with numbers drawn  from various probability distribution
#  With a given mean and standard deviation
# the function np.random.normal
X = np.random.normal(0, 0.1, size=(1000, 1000))
print(X)

# This creates a 1000 by 1000  array of random floats drawn from a normal distribution with the mean of zero
# and a standard deviation of 0.1



print('mean:', X.mean())
print('std:', X.std())
print('max:', X.max())
print('min:', X.min())
print('# positive:', (X > 0).sum())
print('# negative:', (X > 0).sum())

[[-0.07099388 -0.00269245  0.03485536 ... -0.07017458  0.27205219
   0.20028117]
 [-0.07435375  0.13293537  0.01575306 ...  0.01618269 -0.00765113
  -0.25480597]
 [ 0.03397812 -0.19808064 -0.0583969  ... -0.06955354  0.00917668
   0.01812473]
 ...
 [ 0.27920915 -0.00664368  0.15718524 ...  0.0276174   0.22913603
  -0.22738693]
 [ 0.04839288  0.06903868  0.18392936 ... -0.21844349  0.22148843
   0.03515958]
 [-0.04778879 -0.05936496 -0.01945286 ... -0.15853519 -0.02918559
   0.08068978]]
mean: -3.8359050927723095e-05
std: 0.09996533363235116
max: 0.499531764533708
min: -0.48174936228931
# positive: 499842
# negative: 499842
