#### Slicing is performed by combining indices with the colon : symbol inside the square brackets. In general you will come across three types of slicing:

1. ndarray[start:end]
2. ndarray[start:]
3. ndarray[:end]

The first method is used to select elements between the start and end indices. The second method is used to select all elements from the start index till the last index. The third method is used to select all elements from the first index till the end index.

#### Slicing in a 2-D ndarray

In [1]:
import numpy as np
# We create a 4 x 5 ndarray that contains integers from 0 to 19
X = np.arange(20).reshape(4, 5)

# We print X
print()
print('X = \n', X)
print()

# We select all the elements that are in the 2nd through 4th rows and in the 3rd to 5th columns
# (The 1st being index 0)
Z = X[1:4,2:5]

# We print Z
print('Z = \n', Z)

# We can select the same elements as above using method 2
W = X[1:,2:5]

# We print W
print()
print('W = \n', W)

# We select all the elements that are in the 1st through 3rd rows and in the 3rd to 4th columns
Y = X[:3,2:5]

# We print Y
print()
print('Y = \n', Y)

# We select all the elements in the 3rd row
v = X[2,:]

# We print v
print()
print('v = ', v)

# We select all the elements in the 3rd column
q = X[:,2]

# We print q
print()
print('q = ', q)

# We select all the elements in the 3rd column but return a rank 2 ndarray
R = X[:,2:3]

# We print R
print()
print('R = \n', R)


X = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

Z = 
 [[ 7  8  9]
 [12 13 14]
 [17 18 19]]

W = 
 [[ 7  8  9]
 [12 13 14]
 [17 18 19]]

Y = 
 [[ 2  3  4]
 [ 7  8  9]
 [12 13 14]]

v =  [10 11 12 13 14]

q =  [ 2  7 12 17]

R = 
 [[ 2]
 [ 7]
 [12]
 [17]]


### Slicing and editing elements in a 2-D ndarray

In [2]:
# We create a 4 x 5 ndarray that contains integers from 0 to 19
X = np.arange(20).reshape(4, 5)

# We print X
print()
print('X = \n', X)
print()

# We select all the elements that are in the 2nd through 4th rows and in the 3rd to 4th columns
Z = X[1:4,2:5]

# We print Z
print()
print('Z = \n', Z)
print()

# We change the last element in Z to 555
Z[2,2] = 555

# We print X
print()
print('X = \n', X)
print()


X = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


Z = 
 [[ 7  8  9]
 [12 13 14]
 [17 18 19]]


X = 
 [[  0   1   2   3   4]
 [  5   6   7   8   9]
 [ 10  11  12  13  14]
 [ 15  16  17  18 555]]



### numpy.ndarray.copy
Syntax: ndarray.copy(order='C')
https://numpy.org/doc/stable/reference/generated/numpy.ndarray.copy.html

However, if we want to create a new ndarray that contains a copy of the values in the slice we need to use the np.copy() function. The np.copy(ndarray) function creates a copy of the given ndarray. This function can also be used as a method, in the same way as we did before with the reshape function. 

### Demonstrate the copy() function
using the copy command, we are creating new ndarrays that are completely independent of each other.

In [3]:
# We create a 4 x 5 ndarray that contains integers from 0 to 19
import numpy as np

X = np.arange(20).reshape(4, 5)

# we print X
print()
print('X = \n', X)
print()

# create a copy of the slice using np.copy() function
Z = np.copy(X[1:4, 2:5])
print('Z = \n', Z)
print()

# create a copy of the slice using copy as a method
W = X[1:4,2:5].copy()
print('W = \n', W)
print()

# We change the last element in Z to 555
Z[2,2] = 555
print('Z with last element changed = \n', Z)
print()

# we change the last element in W to 444
W[2,2] = 444
print('W with last changed element = \n', W)
print()


X = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

Z = 
 [[ 7  8  9]
 [12 13 14]
 [17 18 19]]

W = 
 [[ 7  8  9]
 [12 13 14]
 [17 18 19]]

Z with last element changed = 
 [[  7   8   9]
 [ 12  13  14]
 [ 17  18 555]]

W with last changed element = 
 [[  7   8   9]
 [ 12  13  14]
 [ 17  18 444]]



### Use an array as indices to either make slices, select, or change elements

In [4]:
# We create a 4 x 5 ndarray that contains integers from 0 to 19
X = np.arange(20).reshape(4, 5)

# we create a rank 1 ndarray that will serve as indices to select elements from X
indices = np.array([1,3])

# We print x
print()
print('X = \n', X)
print()

# we print indices
print('indices = ', indices)
print()

# we use indices ndarray to select the 2nd and 4th row of x
Y = X[indices,:]

# we use the indices ndarray to select the 2nd and 4th column of x
Z = X[:, indices]

# we print Y
print()
print('Y = \n', Y)

# we print Z
print()
print('Z = \n', Z)


X = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

indices =  [1 3]


Y = 
 [[ 5  6  7  8  9]
 [15 16 17 18 19]]

Z = 
 [[ 1  3]
 [ 6  8]
 [11 13]
 [16 18]]


### Use an array as indices to extract specific rows from a rank 2 ndarray.

In [5]:
import numpy as np
# Let's create a rank 2 ndarray
X = np.random.randint(1,20, size=(50,5))
print("Shape of X is: ", X.shape)
print(X)

# Create a rank 1 ndarray that contains a randomly chosen 10 values `0` to `len(X)` (50)
# The row_indices would represent the indices of rows of X
row_indices = np.random.randint(0,50, size=10)
print("Random 10 indices are: ", row_indices)

Shape of X is:  (50, 5)
[[17 12 10  1  2]
 [19  8  7 17 19]
 [16 16 11 10 16]
 [13  6 17  2 18]
 [16  7 16  2 15]
 [11 15  6 12  9]
 [12 15  3 13  8]
 [ 2 15 18  2  8]
 [10  9  2 18 14]
 [ 3 16 15  3  9]
 [ 2 19  7 17 14]
 [17  7 10  1 19]
 [ 2 17 14  9  5]
 [16  6  8  7 19]
 [ 5 11  6  6 13]
 [ 1  5  4  5  2]
 [ 9 16 13 12  2]
 [11  8 10 15  4]
 [ 3 10  1 15  1]
 [ 3 18 13 11 10]
 [ 5  4  1  3 12]
 [12  4  7  5  5]
 [ 4  8 13 19  7]
 [10  7 17  7 16]
 [18  5  7  5  3]
 [ 5 11 13 14 16]
 [ 8  3  7 18 13]
 [13 12 10 17 14]
 [14  1 13  9  6]
 [ 5 12 12  4  8]
 [12  8 17 16  7]
 [13 18 13 15  1]
 [ 9 11 15  4 17]
 [12  2 13  7  7]
 [ 4  3  5 14  6]
 [10 18 13 11 18]
 [ 3  7 10  1 15]
 [13 10  5 14  8]
 [16 19 18  4 16]
 [15  5  5 17  6]
 [ 9  8  3 12  1]
 [16 18  5 10 19]
 [17 19  2  8  4]
 [15  7  1  6 18]
 [ 2 19 11 17  4]
 [18  7 19  9 12]
 [ 2 15 18  1  9]
 [16 19  7 17 18]
 [17 14 11  1 19]
 [12 19 19 15  1]]
Random 10 indices are:  [28 22 36 37 41 48 13 10 10 41]


In [6]:
# To Do 1 - Print those rows of X whose indices are represented by entire row_indices ndarray
# Hint - Use the row_indices ndarray to select specified rows of X
X_subset = X[row_indices, :]
print(X_subset)

# To Do 2 - Print those rows of X whose indices are present in row_indices[4:8]
X_subset = X[row_indices[4:8], :]
print(X_subset)

[[14  1 13  9  6]
 [ 4  8 13 19  7]
 [ 3  7 10  1 15]
 [13 10  5 14  8]
 [16 18  5 10 19]
 [17 14 11  1 19]
 [16  6  8  7 19]
 [ 2 19  7 17 14]
 [ 2 19  7 17 14]
 [16 18  5 10 19]]
[[16 18  5 10 19]
 [17 14 11  1 19]
 [16  6  8  7 19]
 [ 2 19  7 17 14]]


### numpy.diag
Syntax:

numpy.diag(array, k=0)

It extracts or constructs the diagonal elements.
[numpy.diag refrence](https://numpy.org/doc/stable/reference/generated/numpy.diag.html)
NumPy also offers built-in functions to select specific elements within ndarrays. For example, the np.diag(ndarray, k=N) function extracts the elements along the diagonal defined by N. As default is k=0, which refers to the main diagonal. Values of k > 0 are used to select elements in diagonals above the main diagonal, and values of k < 0 are used to select elements in diagonals below the main diagonal. 


### Demonstrate the diag() function


In [7]:
import numpy as np
# We create a 5 x 5 ndarray that contains integers from 0 to 24
X = np.arange(25).reshape(5, 5)

# We print X
print()
print('X = \n', X)
print()

# We print the elements in the main diagonal of X
print('z =', np.diag(X))
print()

# We print the elements above the main diagonal of X
print('y =', np.diag(X, k=1))
print()

# We print the elements below the main diagonal of X
print('w = ', np.diag(X, k=-1))


X = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

z = [ 0  6 12 18 24]

y = [ 1  7 13 19]

w =  [ 5 11 17 23]


### numpy.unique
Syntax:

numpy.unique(array, return_index=False, return_inverse=False, return_counts=False, axis=None)

It returns the sorted unique elements of an array.[Manipulating arrays using numpy.unique](https://numpy.org/doc/stable/reference/generated/numpy.unique.html) 
It is often useful to extract only the unique elements in an ndarray. We can find the unique elements in an ndarray by using the np.unique() function. The np.unique(ndarray) function returns the unique elements in the given ndarray.

#### Demonstrate the unique() function

In [8]:
# Create 3 x 3 ndarray with repeated values
X = np.array([[1,2,3],[5,2,8],[1,2,3]])

# We print X
print()
print('X = \n', X)
print()

# We print the unique elements of X 
print('The unique elements in X are:',np.unique(X))


X = 
 [[1 2 3]
 [5 2 8]
 [1 2 3]]

The unique elements in X are: [1 2 3 5 8]


[Indexing on ndarrays - Reference Document](https://numpy.org/doc/stable/user/basics.indexing.html)