# Using Built-in Functions to Create ndarrays
[Reference docs on array Creation](https://numpy.org/doc/stable/user/basics.creation.html#array-creation)

In [1]:
import numpy as np

my_list = [1,2,3,4,5]
np.array(my_list)

array([1, 2, 3, 4, 5])

#### 1. Create a Numpy array of zeros with a desired shape

In [2]:
# Create a 3 x 4 ndarray full of zeros.
X = np.zeros((3,4), dtype=int)

# we print x
print()
print('X = \n', X)
print()

# we print information about x
print('X has dimension:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype)


X = 
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

X has dimension: (3, 4)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: int64


#### 2.Create a Numpy array of ones

In [3]:
# We create a 3 x 2 ndarray full of ones.
X = np.ones((3,2))

# we print x
print()
print('X = \n', X)
print()

# we print information about x
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype)


X = 
 [[1. 1.]
 [1. 1.]
 [1. 1.]]

X has dimensions: (3, 2)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: float64


#### 3. Create a Numpy array of constants

In [4]:
# we create a 2 x 3 ndarray full of fives.
X = np.full((2,3), 5)

# we print x
print()
print('X = \n', X)
print()

# we print information about x
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype)


X = 
 [[5 5 5]
 [5 5 5]]

X has dimensions: (2, 3)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: int64


#### 4.Create a  Numpy array of identity matrix

In [5]:
# we create a 5 x 5 Identity matrix
X = np.eye(5)

# We print X
print()
print('X = \n', X)
print()

# we print information of x
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))


X = 
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

X has dimensions: (5, 5)
X is an object of type: <class 'numpy.ndarray'>


#### 5.Create a Numpy array of constants

In [6]:
# Create a 4 x 4 diagonal matrix that contains the numbers 10, 20, 30, and 50
# on its main diagonal
X = np.diag([10,20,30,50])

# we print X
print()
print('X = \n', X)
print()


X = 
 [[10  0  0  0]
 [ 0 20  0  0]
 [ 0  0 30  0]
 [ 0  0  0 50]]



#### 6.Create a Numpy array of evenly spaced values in a given range, using arange(stop_val)
[https://numpy.org/doc/stable/reference/generated/numpy.arange.html](http://)

In [7]:
# we create a rank 1 ndarray that has sequential integers from 0 to 9
x = np.arange(10)

# we print the ndarray
print()
print('x = ', x)
print()

# we print information about the ndarray
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype)


x =  [0 1 2 3 4 5 6 7 8 9]

x has dimensions: (10,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: int64


#### 7.Create a Numpy array using arange(start_val, stop_val)

In [8]:
# we create a rank 1 ndarray that has sequential integers from 4 to 9.
x = np.arange(4, 10)

# we print the ndarray
print()
print('x = ', x)
print()

# we print information about the ndarray
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype)


x =  [4 5 6 7 8 9]

x has dimensions: (6,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: int64


##### Create a Numpy array using arange(start_val, stop_val, step_size)

In [9]:
# We create a rank 1 ndarray that has evenly spaced integers from 1 to 13 in steps of 3.
x = np.arange(1,14,3)

# we print the ndarray
print()
print('x = ', x)
print()

# we print information about ndarray
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype)


x =  [ 1  4  7 10 13]

x has dimensions: (5,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: int64


#### 8.Create a numpy array using linspace(start, stop, n), with stop inclusive
###### References
[Reference/Docs](https://numpy.org/doc/stable/reference/generated/numpy.linspace.html)

In [10]:
# we create a rank 1 ndarray that has 10 integers evenly spaced between 0 and 25
x = np.linspace(0,25,10)

# print the ndarray
print()
print('x = \n', x)
print()

# we print information about ndarray
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype)


x = 
 [ 0.          2.77777778  5.55555556  8.33333333 11.11111111 13.88888889
 16.66666667 19.44444444 22.22222222 25.        ]

x has dimensions: (10,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: float64


#### Create a Numpy array using linspace(start, stop, n), with stop excluded

In [11]:
# Creating a rank 1 ndarray that has 10 integers evenly spaced between 0 and 25,
# with 25 excluded
x = np.linspace(0,25,10, endpoint = False)

# Print the ndarray
print()
print('x = ', x)
print()

# we print information about the ndarray
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The element in x are of type:', x.dtype)


x =  [ 0.   2.5  5.   7.5 10.  12.5 15.  17.5 20.  22.5]

x has dimensions: (10,)
x is an object of type: <class 'numpy.ndarray'>
The element in x are of type: float64


#### 9.Create a Numpy array by feeding the output of arange() function to the reshape() function.
Here arange() function will give you a 1-D array, whereas the reshape() function will convert that 1-D array into a desired shape.
NB: The size() of the final output must be as same as size of initial 1-D array.

In [12]:
# We create a rank 1 ndarray with sequential integers from 0 to 19
x = np.arange(20)

# we print x
print()
print('Original x = ', x)
print()

# we reshape x into a 4 x 5 ndarray
x = np.reshape(x, (4,5))

# we print the reshaped x
print()
print('Reshaped x = \n', x)
print()

# we print the information about reshaped x
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype)


Original x =  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


Reshaped x = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

x has dimensions: (4, 5)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: int64


#### 10 Create a Numpy array by calling the reshape() function from the output of arange() function.

###### changing in arguments of reshape()


In [13]:
# We create a rank 1 ndarray with sequential integers from 0 to 19 and
# reshape it to a 4 x 5 array
Y = np.arange(20).reshape(4, 5)

# we print Y
print()
print('Y = \n', Y)
print()

# we peint information about Y
print('Y has dimensions:', Y.shape)
print('Y is an object of type:', type(Y))
print('The elements in Y are of type:', Y.dtype)


Y = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

Y has dimensions: (4, 5)
Y is an object of type: <class 'numpy.ndarray'>
The elements in Y are of type: int64


#### 11. Create a rank 2 Numpy array by using the reshape() function

In [14]:
# We create a rank 1 ndarray with 10 integers evenly spaced between 0 and 50,
# with 50 excluded. we then reshape it to a 5 x 2 ndarray
X = np.linspace(0,50,10, endpoint=False).reshape(5,2)

# we print x
print()
print('X = \n', X)
print()

# we print information about x
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype)


X = 
 [[ 0.  5.]
 [10. 15.]
 [20. 25.]
 [30. 35.]
 [40. 45.]]

X has dimensions: (5, 2)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: float64


#### 12. Create a Numpy array using numpy.random.random() function

In [15]:
# We create a 3 x 3 ndarray with random floats in the half-open interval [0.0, 1.0].
X = np.random.random((3,3))

# we print x
print()
print('X = \n', X)
print()

# we print information about x
print('X has dimensions:', X.shape)
print('X in an object of type:', type(X))
print('The elements in X are of type:', X.dtype)


X = 
 [[0.7733718  0.26019458 0.96786062]
 [0.83044122 0.69059225 0.33351742]
 [0.06266242 0.99234747 0.83525091]]

X has dimensions: (3, 3)
X in an object of type: <class 'numpy.ndarray'>
The elements in X are of type: float64


#### 13.Create a Numpy array using the numpy.random.randint() function

In [16]:
# We create a 3 x 2 ndarray with random integers in the half-open interval [4, 15].
X = np.random.randint(4,15,size=(3,2))

# we print x
print()
print('X = \n', X)
print()

# we print information about X
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype)


X = 
 [[ 9 13]
 [10  5]
 [14  5]]

X has dimensions: (3, 2)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: int64


#### 14.Create a Numpy array of "Normal" distributed random numbers, using the numpy.random.normal() function.

In [17]:
# We create a 1000 x 1000 ndarray of random floats drawn from normal (Gaussian) distribution
# with a mean of zero and a standard deviation of 0.1.
X = np.random.normal(0, 0.1, size=(1000,1000))

# we print X
print()
print('X = \n', X)
print()

# we print information about x
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype)
print('The elements in X havea mean of:', X.mean())
print('The maximum value in X is:', X.max())
print('The minimum value in X is:', X.min())
print('X has',(X < 0).sum(), 'negative numbers')
print('X has', (X > 0).sum(), 'positive numbers')


X = 
 [[-0.07028194  0.12853633  0.01233087 ...  0.00497279 -0.19040019
   0.08339382]
 [-0.11231018 -0.02053772  0.14992123 ...  0.02432006 -0.03767157
   0.03583615]
 [-0.15825559  0.12315188  0.06242792 ... -0.00599389 -0.06414739
   0.10896721]
 ...
 [-0.01422041  0.13286709 -0.03186908 ... -0.08231412 -0.19226558
  -0.01311235]
 [-0.00931117 -0.03786446 -0.115826   ... -0.03041999  0.21911327
   0.20977984]
 [-0.03179213  0.1589072  -0.07372158 ... -0.04066027  0.01880113
  -0.09103068]]

X has dimensions: (1000, 1000)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: float64
The elements in X havea mean of: -0.0001344753364444306
The maximum value in X is: 0.516202995124027
The minimum value in X is: -0.4847743715386253
X has 499950 negative numbers
X has 500050 positive numbers


###  Using the NumPy functions you learned to create a 4 x 4 ndarray that only contains consecutive even numbers from 2 to 32 (inclusive).

In [18]:
# Function to confirm the correct answer
def check_answer(X):
    solution = np.arange(2, 34, 2).reshape(4, 4)

    if type(X) != np.ndarray:
        print("`X` should be an ndarray")
    elif np.array_equal(X, solution):
        print("Nice work! You can view my solution below")
    elif X.shape != solution.shape:
        print("Your answer for `X` has a shape of {} but it should be 4 x 4".format(X.shape))
    else:
        print("Your answer for `X` has the right shape but incorrect values")

import numpy as np
# You can use either the np.arange function 
# or the np.linspace function to generate the numbers, then the .reshape method to create the 4 x 4 shape.
X = np.arange(2,34,2).reshape(4,4)
X = np.linspace(2,32,16).reshape(4,4) # Alternative 2

check_answer(X)



Nice work! You can view my solution below
